services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Hexagon\:
        resource: '../tests/Hexagon/*'

    App\Domain\Repository\WordRepositoryInterface:
        class: App\Tests\__Mock__\WordInMemoryRepository

    App\Domain\UseCase\PlayGameUseCase:
        arguments:
            - '@App\Domain\Repository\WordRepositoryInterface'
            - '%max_attempts%'

    App\Tests\Cli\Bdd\CliPlayContext:
        arguments:
            - '@App\Domain\UseCase\PlayGameUseCase'